services:
  alloy:
    image: grafana/alloy:latest
    container_name: alloy
    hostname: UbuntuServer1
    restart: unless-stopped
    # logging:
    #   driver: loki
    #   options:
    #     loki-url: "https://loki.fjrg.net/loki/api/v1/push"
    #     loki-retries: 2
    #     loki-max-backoff: 800ms
    #     loki-timeout: 1s
    #     keep-file: "true"
    #     mode: "non-blocking"
    command:
      - run
      - --server.http.listen-addr=0.0.0.0:12345
      - --storage.path=/var/lib/alloy/data
      - /etc/alloy/config.alloy
    ports:
      - 12345:12345
    volumes:
      - ./config.alloy:/etc/alloy/config.alloy
      - ~/docker_volumes/alloy/data:/var/lib/alloy/data
      - /:/rootfs:ro
      - /run:/run:ro
      - /var/log:/var/log:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker/:ro
      - /run/udev/data:/run/udev/data:ro
